using System;

namespace DispCore.Events
{
	public enum CallEventTypes
	{
		CALL_INCOMING,
		CALL_INPROGRESS,
		CALL_RINGING,
		CALL_EARLY_MEDIA,
		CALL_CONNECTED,
		CALL_TERMWAIT,
		CALL_DISCONNECTED,
		CALL_LOCAL_HOLD_OK,
		CALL_LOCAL_HOLD_NOK,
		CALL_LOCAL_RESUME_OK,
		CALL_LOCAL_RESUME_NOK,
		CALL_REMOTE_HOLD,
		CALL_REMOTE_RESUME,
		CALL_MEDIA_UPDATING,
		CALL_MEDIA_UPDATED
	}
}
