using System;

namespace DispCore.Trunk.Types
{
	public enum TrunkCallReleaseReason
	{
		TCRL_ACCEPT = 1,
		TCRL_HALAFACCEPT,
		TCRL_GENREJECT,
		TCRL_CALLEEREJECT,
		TCRL_TCNREJECT,
		TCRL_TCNUNREG,
		TCRL_GEN_RESEAVE = 64,
		TCRL_GENRELEASE,
		TCRL_CALLERRELEASE,
		TCRL_TCNENHANCERELEASE,
		TCRL_OVERTIMERELEASE,
		TCRL_CALLEERELASE,
		TCRL_DCCANCELVEDIOPUSH,
		TCRL_TCNCANCELVEDIOPUSH,
		TCRL_CALL_PRI_RESERVER = 128,
		TCRL_CALL_PRI_GEN_RELEASE,
		TCRL_CALL_PRI_PTT_RELEASE,
		TCRL_CALL_PRI_TCN_RELEASE,
		TCRL_CALL_PRI_OVE_RELEASE,
		TCRL_CALL_PRI_DG_RELEASE = 192
	}
}
